### ISSUE TITLE
Cant upload files to public shares in a groupfolders with advanced permissions on

### ISSUE THREAD

**Issue by small1** [nextcloud/groupfolders#811]
I am using nextcloud 18.0.1 and 18.0.2 

This worked on 6.0.1 but does not work in 6.0.3   

Error from nextcloud log: 

{"reqId":"jC7AB57bmzB0aKbbRD9z","level":3,"time":"2020-03-20T06:32:46+00:00","remoteAddr":"41.86.35.64","user":"--","app":"public","method":"PUT","url":"/public.php/webdav/shield.png","message":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":638,"function":"getOwner","class":"OC\\Files\\View","type":"->","args":["/Bernhardsson/Test/Test//shield (2).png"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":190,"function":"getSourcePathAndOwner","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/Bernhardsson/Test/Test//shield (2).png"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":148,"function":"addNotificationsForFileAction","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/Bernhardsson/Test/Test//shield (2).png","file_created","","created_public"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooksStatic.php","line":47,"function":"fileCreate","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/Bernhardsson/Test/Test//shield (2).png"]},{"file":"/var/www/nextcloud/lib/private/legacy/hook.php","line":111,"function":"fileCreate","class":"OCA\\Activity\\FilesHooksStatic","type":"::","args":[{"path":"/Bernhardsson/Test/Test//shield (2).png"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":389,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_create",{"path":"/Bernhardsson/Test/Test//shield (2).png"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":321,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["shield (2).png",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["shield (2).png",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.ingenstans.net/public.php/webdav/shield.png","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https://cloud.ingenstans.net/public.php/webdav/shield.png","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https://cloud.ingenstans.net/public.php/webdav/shield.png","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.ingenstans.net/public.php/webdav/shield.png","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":109,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/View.php","Line":1690,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36","version":"18.0.2.2"}

**Comment by small1** [comment]
his has been tested on three different servers

**Comment by small1** [comment]
After one more test .. it might be nextcloud server 18.0.2 after all, i will try this on one more server

**Comment by deflektor-de** [comment]
Duplicate of #486

**Comment by small1** [comment]
this is not a duplicate. for me it has worked on nc16 and nc17 and nc18 it 
doesnt work on nc18.0.1 or 18.0.2

/Johan

**Comment by mesiah1970-haydar** [comment]
I have the same issue on NC 18.0.2 but not on 18.0.1

**Comment by mesiah1970-haydar** [comment]
Hello I just investigated again, the version 6.0.3 of Group Folders is buggy and leads external guest to errors like unknown error:
SO DO NOT UPDATE TO 6.0.3

and this is the error


Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "photos.page.index" as such route does not exist. |   | März 23, 2020 10:32:28
-- | -- | --
Error | public | Error: Call to undefined method OCP\Files\Cache\CacheInsertEvent::setPath()/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 247:OCA\GroupFolders\CacheListener->onCacheEvent(OCP\Files\Ca ... {}, "OCP\\Files\ ... t", Symfony\Comp ... {})/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:Symfony\Component\EventDispatcher\EventDispatcher->callListeners([ Closure {},Closure {}], "OCP\\Files\ ... t", OCP\Files\Ca ... {})/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 80:Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCP\Files\Ca ... {}, "OCP\\Files\ ... t")/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php - line 63:OC\EventDispatcher\EventDispatcher->dispatch("OCP\\Files\ ... t", OCP\Files\Ca ... {})/var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 305:OC\EventDispatcher\SymfonyAdapter->dispatch("OCP\\Files\ ... t", OCP\Files\Ca ... {})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 130:OC\Files\Cache\Cache->insert("__groupfold ... f", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php - line 123:OC\Files\Cache\Wrapper\CacheWrapper->insert("__groupfold ... f", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 130:OC\Files\Cache\Wrapper\CacheJail->insert("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/apps/groupfolders/lib/Mount/RootEntryCache.php - line 57:OC\Files\Cache\Wrapper\CacheWrapper->insert("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 130:OCA\GroupFolders\Mount\RootEntryCache->insert("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 130:OC\Files\Cache\Wrapper\CacheWrapper->insert("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 116:OC\Files\Cache\Wrapper\CacheWrapper->insert("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 293:OC\Files\Cache\Wrapper\CacheWrapper->put("*** sensiti ... *", { mimetype: ... "})/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 222:OC\Files\Cache\Scanner->addToCache("*** sensiti ... *", { mimetype: ... "}, -1)/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 337:OC\Files\Cache\Scanner->scanFile("*** sensiti ... *", 3, 5554, false, false)/var/www/nextcloud/lib/private/Files/Cache/Updater.php - line 124:OC\Files\Cache\Scanner->scan("*** sensiti ... *", false, 3, false)/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 291:OC\Files\Cache\Updater->update("*** sensiti ... *")/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:OCA\DAV\Connector\Sabre\File->put(null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:OCA\DAV\Connector\Sabre\Directory->createFile("*** sensiti ... *", null)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525:Sabre\DAV\Server->createFile("*** sensiti ... *", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php - line 109:Sabre\DAV\Server->exec()/var/www/nextcloud/public.php - line 81:require_once("/var/www/ne ... p")

**Comment by mesiah1970-haydar** [comment]
Yeah the upload on public links is kind of buggy, I just replaced the version to 6.0.1 and works like a charm. So the point is to update the NC from 18.0.1 to 18.0.2 but not update the buggy GF Apps. However the GF updates automatically to 6.0.3 whil update NC to 18.0.2, but you can only downgrade this app again to 6.01

**Comment by mesiah1970-haydar** [comment]
And here are some further error, when I try to delte a file as an extarnal from external share. This spits also an unknown error:

I'm using NC 18.0.3 with GF 6.0.3

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route “photos.page.index” as such route does not exist.

/var/www/nextcloud/lib/private/Route/Router.php - line 339:Symfony\Component\Routing\Generator\UrlGenerator->generate(“photos.page.index”, [], 1)

/var/www/nextcloud/lib/private/URLGenerator.php - line 82:OC\Route\Router->generate(“photos.page.index”, [])

/var/www/nextcloud/lib/private/NavigationManager.php - line 293:OC\URLGenerator->linkToRoute(“photos.page.index”)

/var/www/nextcloud/lib/private/NavigationManager.php - line 114:OC\NavigationManager->init()

/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php - line 182:OC\NavigationManager->getAll(“guest”)

/var/www/nextcloud/lib/private/legacy/defaults.php - line 263:OCA\Theming\ThemingDefaults->getShortFooter()

/var/www/nextcloud/lib/public/Defaults.php - line 169:OC_Defaults->getLongFooter()

/var/www/nextcloud/core/templates/layout.guest.php - line 55:OCP\Defaults->getLongFooter()

/var/www/nextcloud/lib/private/Template/Base.php - line 179:include("/var/www/ne … p")

/var/www/nextcloud/lib/private/Template/Base.php - line 151:OC\Template\Base->load("/var/www/ne … p", null)

/var/www/nextcloud/lib/private/legacy/template.php - line 181:OC\Template\Base->fetchPage(null)

/var/www/nextcloud/lib/private/legacy/template.php - line 212:OC_Template->fetchPage(null)

/var/www/nextcloud/lib/private/Template/Base.php - line 132:OC_Template->fetchPage()

/var/www/nextcloud/lib/private/legacy/template.php - line 333:OC\Template\Base->printPage()

/var/www/nextcloud/public.php - line 94:OC_Template::printExceptionErrorPage(Error {}, 500) März 27, 2020 08:08:30
Error public Error: Call to a member function getUID() on null

/var/www/nextcloud/apps/activity/lib/FilesHooks.php - line 638:OC\Files\View->getOwner("/Kundenname … f")

/var/www/nextcloud/apps/activity/lib/FilesHooks.php - line 190:OCA\Activity\FilesHooks->getSourcePathAndOwner("/Kundenname … f")

/var/www/nextcloud/apps/activity/lib/FilesHooks.php - line 165:OCA\Activity\FilesHooks->addNotificationsForFileAction("/Kundenname … f", “file_deleted”, “deleted_self”, “deleted_by”)

/var/www/nextcloud/apps/activity/lib/FilesHooksStatic.php - line 63:OCA\Activity\FilesHooks->fileDelete("/Kundenname … f")

/var/www/nextcloud/lib/private/legacy/hook.php - line 111:OCA\Activity\FilesHooksStatic::fileDelete({ run: true, … "})

/var/www/nextcloud/lib/private/Files/View.php - line 1275:OC_Hook::emit(“OC_Filesystem”, “delete”, { run: true, … "})

/var/www/nextcloud/lib/private/Files/View.php - line 1145:OC\Files\View->runHooks([ “delete”], “/Kundenname … f”)

/var/www/nextcloud/lib/private/Files/View.php - line 716:OC\Files\View->basicOperation(“unlink”, “Lieferschein 2019-10589.pdf”, [ “delete”])

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 448:OC\Files\View->unlink(“Lieferschein 2019-10589.pdf”)

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179:OCA\DAV\Connector\Sabre\File->delete()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 287:Sabre\DAV\Tree->delete(“Lieferschein 2019-10589.pdf”)

<>Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\R … "}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ … "], [ Sabre\HTTP … }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit(“method:DELETE”, [ Sabre\HTTP … }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R … "}, Sabre\HTTP\Response {})

/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php - line 109:Sabre\DAV\Server->exec()

/var/www/nextcloud/public.php - line 81:require_once("/var/www/ne … p")

**Comment by iexos** [comment]
Same error messages as OP on deletion in public share.

Web UI tells an error for upload/folder creation as well as deletion, however upload & creation works (still there after refresh), deletion does not (have to use logged in user to delete).

**Comment by critot** [comment]
Also for me, same errors as OP, same comment as @iexos, please resolve we're in production mode, thank you

**Comment by small1** [comment]
So with the latest 6.0.4 i can upload a file as a guest when i have upload and edit turned on. But file drop does not work still.

Ping @juliushaertl @icewind1991 @rullzer this is a quite annoying bug.

**Comment by mesiah1970-haydar** [comment]
Hey small1,

what do you mean with file drop? Do you mean file delete?

Rgds

Haydar

**Comment by small1** [comment]
@mesiah1970-haydar when you share a folder as a public link you can choose between read only,  allow upload and editing and filedrop.

![Screenshot from 2020-04-06 14-05-51](https://user-images.githubusercontent.com/317830/78556761-d6189800-780f-11ea-8591-1c860ec63aca.png)

**Comment by mesiah1970-haydar** [comment]
Oh, thanks for the insight, so my question would be, if it is possible to **delete** files upload by an guest or host from a public share. I guess file drop I don't use

Rgds

Haydar

**Comment by small1** [comment]
@mesiah1970-haydar yes on upload and edit permission they should be able to delete a file. I can do that on My instances with groupfolders. But it might depend on the rights of the user creating the share.

**Comment by mesiah1970-haydar** [comment]
Ok thanks, I'll give a try and tell you the results.

**Comment by mesiah1970-haydar** [comment]
Hello all

I can confirm now, that GF with Version 6.0.4 is working now:

1. Upload to public share is without an error
2. deletion of an file in the public share is without an error
3. File drop is on my installation of Nextcloud (no docker, just VM) is without an error

Rgds

Haydar

**Comment by small1** [comment]
File drop does not work. Still gives an error on my instances on debian 9 with php 7.2 and nginx

**Comment by mesiah1970-haydar** [comment]
an error log from your NC instance while you're dropping files would be fine to the developers for investigation.

**Comment by critot** [comment]
I confirm that GF with Version 6.0.4 is working correctly
NC 18.0.3, GF 6.0.4, Ubuntu18, nginx
thank you!

**Comment by small1** [comment]
> an error log from your NC instance while you're dropping files would be fine to the developers for investigation.

id did at the start of this bug request. But now when i check again i do have a different error.

**Comment by small1** [comment]
`
{"reqId":"8Eb6idvowPZ8whECiOKi","level":3,"time":"2020-04-08T09:17:56+00:00","remoteAddr":"2.69.234.55","user":"--","app":"public","method":"PUT","url":"/public.php/webdav/GDPR%20kit.png","message":{"Exception":"Error","Message":"Call to a member function getType() on boolean","Code":0,"Trace":[{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":109,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/ServerFactory.php","Line":156,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0"}
{"reqId":"8Eb6idvowPZ8whECiOKi","level":3,"time":"2020-04-08T09:17:56+00:00","remoteAddr":"2.69.234.55","user":"--","app":"core","method":"PUT","url":"/public.php/webdav/GDPR%20kit.png","message":{"Exception":"Error","Message":"Call to a member function getType() on boolean","Code":0,"Trace":[{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":109,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/ServerFactory.php","Line":156,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0"}
{"reqId":"8Eb6idvowPZ8whECiOKi","level":3,"time":"2020-04-08T09:17:56+00:00","remoteAddr":"2.69.234.55","user":"--","app":"core","method":"PUT","url":"/public.php/webdav/GDPR%20kit.png","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php","line":90,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Template/JSCombiner.php","line":125,"function":"getContent","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Template/JSCombiner.php","line":102,"function":"isCached","class":"OC\\Template\\JSCombiner","type":"->","args":["merged-template-prepend.js.deps",{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"}]},{"file":"/var/www/nextcloud/lib/private/Template/JSResourceLocator.php","line":115,"function":"process","class":"OC\\Template\\JSCombiner","type":"->","args":["/var/www/nextcloud","core/js/merged-template-prepend.json","core"]},{"file":"/var/www/nextcloud/lib/private/Template/JSResourceLocator.php","line":71,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->","args":["/var/www/nextcloud","core/js/merged-template-prepend.json"]},{"file":"/var/www/nextcloud/lib/private/Template/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->","args":["js/merged-template-prepend"]},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":346,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/en","files_sharing/l10n/en","files_sharing/js/dist/main","search/l10n/en","search/js/searchprovider","js/files/fileinfo","js/files/client"]]},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":174,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/en","files_sharing/l10n/en","files_sharing/js/dist/main","search/l10n/en","search/js/searchprovider","js/files/fileinfo","js/files/client"]]},{"file":"/var/www/nextcloud/lib/private/legacy/template.php","line":184,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["error",""]},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/legacy/template.php","line":333,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/var/www/nextcloud/public.php","line":94,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Error"},500]}],"File":"/var/www/nextcloud/lib/private/Files/Node/File.php","Line":58,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.3.0"}
`

**Comment by small1** [comment]
> I confirm that GF with Version 6.0.4 is working correctly
> NC 18.0.3, GF 6.0.4, Ubuntu18, nginx
> thank you!

@critot Have you tested to create a public share with  file drop rights and uploaded a file to it within a group folder?

**Comment by small1** [comment]
Aahh  found one more variable. Advanced permissions is turned on to the nextcloud instances  that it doesnt work on.

**Comment by small1** [comment]
So thats it as soon as i turn on ACL on the group folder i cant use file drop.

**Comment by mesiah1970-haydar** [comment]
Oh, I didn't try that with advanced permissions, never used it, since I never needed it

**Comment by tsalex** [comment]
I'm also seeing this issue: enabling advanced permissions on the group folder breaks uploading to a sub-folder shared as a File Drop.  

Public users cannot upload unless advanced permissions for the group folder is disabled.

3 errors are returned on my installation when the upload fails:

>[core] Error: OCP\Files\NotPermittedException:  at <<closure>>
>
> 0. /var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php line 90
>    OC\Files\Node\File->getContent()
> 1. /var/www/html/nextcloud/lib/private/Template/JSCombiner.php line 125
>    OC\Files\SimpleFS\SimpleFile->getContent()
> 2. /var/www/html/nextcloud/lib/private/Template/JSCombiner.php line 102
>    OC\Template\JSCombiner->isCached("merged-template-prepend.js.deps", OC\Files\SimpleFS\SimpleFolder {})
> 3. /var/www/html/nextcloud/lib/private/Template/JSResourceLocator.php line 115
>    OC\Template\JSCombiner->process("/var/www/html/nextcloud", "core/js/merged-template-prepend.json", "core")
> 4. /var/www/html/nextcloud/lib/private/Template/JSResourceLocator.php line 71
>    OC\Template\JSResourceLocator->cacheAndAppendCombineJsonIfExist("/var/www/html/nextcloud", "core/js/merged-template-prepend.json")
> 5. /var/www/html/nextcloud/lib/private/Template/ResourceLocator.php line 78
>    OC\Template\JSResourceLocator->doFind("js/merged-template-prepend")
> 6. /var/www/html/nextcloud/lib/private/TemplateLayout.php line 346
>    OC\Template\ResourceLocator->find(["core/js/dist/m ... "])
> 7. /var/www/html/nextcloud/lib/private/TemplateLayout.php line 174
>    OC\TemplateLayout::findJavascriptFiles(["core/js/dist/m ... "])
> 8. /var/www/html/nextcloud/lib/private/legacy/template.php line 184
>    OC\TemplateLayout->__construct("error", "")
> 9. /var/www/html/nextcloud/lib/private/Template/Base.php line 132
>    OC_Template->fetchPage()
>10. /var/www/html/nextcloud/lib/private/legacy/template.php line 333
>    OC\Template\Base->printPage()
>11. /var/www/html/nextcloud/public.php line 94
>    OC_Template::printExceptionErrorPage(Error {}, 500)
>
>PUT /public.php/webdav/what-is-good-customer-service.png



>[core] Error: Error: Call to a member function getType() on boolean at <<closure>>
>
>0. <<closure>>
>   OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
>1. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>   call_user_func_array(Closure {}, ["*** sensitive  ... "])
>2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
>   Sabre\Event\EventEmitter->emit("beforeMethod", ["*** sensitive  ... "])
>3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
>4. /var/www/html/nextcloud/apps/dav/appinfo/v1/publicwebdav.php line 109
>   Sabre\DAV\Server->exec()
>5. /var/www/html/nextcloud/public.php line 81
>   require_once("/var/www/html/n ... p")
>
>PUT /public.php/webdav/what-is-good-customer-service.png




>[public] Error: Error: Call to a member function getType() on boolean at <<closure>>
>
>0. <<closure>>
>   OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
>1. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>   call_user_func_array(Closure {}, ["*** sensitive  ... "])
>2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
>   Sabre\Event\EventEmitter->emit("beforeMethod", ["*** sensitive  ... "])
>3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
>4. /var/www/html/nextcloud/apps/dav/appinfo/v1/publicwebdav.php line 109
>   Sabre\DAV\Server->exec()
>5. /var/www/html/nextcloud/public.php line 81
>   require_once("/var/www/html/n ... p")
>
>PUT /public.php/webdav/what-is-good-customer-service.png

**Comment by remogatto** [comment]
I came across the same issue. I'm using group folder 6.0.4 with Nextcloud 18.0.3. Thank you.

**Comment by mesiah1970-haydar** [comment]
@remogatto 
so your problem is fixed or not?

**Comment by remogatto** [comment]
No. The issue still persists.

**Comment by webftpmaster** [comment]
Same issue. Same updated versions of NC and GF
Only when Advanced Permissions are turned on it gives the error when file drop link is created

Also, to mention that I checked and the files actually DO GET UPLOADED but it still gives you the error

Please Please Please check it asap.  it's extremely confusing for users

Thank you

**Comment by Pilzinsel64** [comment]
I also have exactly the same issue. I am using Nextclodu v18.0.3 and Grou folders version 6.0.5.

**Comment by mesiah1970-haydar** [comment]
Well Pilzinsel,

> I also have exactly the same issue. I am using Nextclodu v18.0.3 and Grou folders version 6.0.5.

Well I've tested your scenario NC 18.03 + GF 6.0.5 and I could not generate such an error. File drop works well. BUT I've read, that with advanced permissions this error occurs. Could you please disable the advanced permissions on the GF and try to upload/drop again?

Haydar

**Comment by Pilzinsel64** [comment]
Oh sorry. Yes, it use advanced permissions.
And yes: I created a test folder. I shared a write-only folder and uploading files to worked well. I enabled advanced permission setting and then it showed me an error while trying upload the file.
Also as described above, the file got uploaded anyway. But not for every shared folder. I don't know on what it depends.

**Comment by Pilzinsel64** [comment]
I found out why it does the file is there only sometimes. It depends if the folder (or path) contains white spaces (%20). It yes, the file is missing and if no, the file is there.
But the error while uploading is still there at anytime if the advanced permissions are setted to on.

**Comment by mesiah1970-haydar** [comment]
well, then this is a issue, which is certainly a bug. But this is mentioned in this issue few times. So the developers should have a look on it. Prior to your issue, we had an upload problem "unknown error" to public shares. This was resolved in 6.0.4. Anyway, some other issues now occurred. like the the advance file permission. Sorry in this case I'm out of options

**Comment by bananabreath** [comment]
I am having the same issue. 
Has there been made any progress on this since April? We are relying on a group folder structure, and we need a file drop folder inside this structure.

**Comment by zaku903** [comment]
Same issue here, Occurred after upgraded NC to 19 (19.0.3 now) and groupfolders to 7.0.0, 
File drop function for public under group folder is needed.

Is there any workaround for it?

**Comment by biva** [comment]
Is this bug still present? Any update?

**Comment by ZeikoFr** [comment]
> Is this bug still present? Any update?

Yes the bug is still present, I've tested this morning on a Nextcloud 20.0.1 and I can't create a "file drop" share when the groupfolder as advanced permissions toggled on

**Comment by cabelodomato** [comment]
Same issue here.

It works perfectly if I turn off the advance permissions. otherwise, uploads don't work via a public link.

Thank you.

**Comment by iljur** [comment]
Exactly same here.

NC 20.0.5
GF 8.2.0

**Comment by pierreozoux** [comment]
I'll close as duplicate of #486
